package principal;

/**
 *
 * @author JoseR
 */
public class actualizarP2 extends javax.swing.JFrame {

    /**
     * Creates new form actualizarP2
     */
    public actualizarP2() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _panelFondo = new javax.swing.JPanel();
        _lblFecha = new javax.swing.JLabel();
        _lblPago = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        _lblClienteMostrar = new javax.swing.JLabel();
        _btnPrincipal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        _txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _lblFecha.setText("Fecha:");

        _lblPago.setText("Pago:");

        jButton1.setText("Proceder con el pago");

        _lblClienteMostrar.setText("Cliente seleccionado");

        _btnPrincipal.setText("Principal");
        _btnPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btnPrincipalMouseClicked(evt);
            }
        });

        _txtResultado.setEditable(false);
        _txtResultado.setColumns(20);
        _txtResultado.setRows(5);
        _txtResultado.setText("Resultado\n/*mostrar si no está \nal día, \no por lo menos los\n ultimos 3 pagos*/");
        jScrollPane1.setViewportView(_txtResultado);

        javax.swing.GroupLayout _panelFondoLayout = new javax.swing.GroupLayout(_panelFondo);
        _panelFondo.setLayout(_panelFondoLayout);
        _panelFondoLayout.setHorizontalGroup(
            _panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_lblClienteMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(_panelFondoLayout.createSequentialGroup()
                        .addGroup(_panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_lblPago)
                            .addGroup(_panelFondoLayout.createSequentialGroup()
                                .addComponent(_lblFecha)
                                .addGap(26, 26, 26)
                                .addGroup(_panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _panelFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_btnPrincipal)
                .addGap(304, 304, 304))
        );
        _panelFondoLayout.setVerticalGroup(
            _panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_panelFondoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addGroup(_panelFondoLayout.createSequentialGroup()
                        .addComponent(_lblClienteMostrar)
                        .addGap(32, 32, 32)
                        .addComponent(_lblFecha)
                        .addGap(21, 21, 21)
                        .addComponent(_lblPago)
                        .addGap(2, 2, 2)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(_btnPrincipal)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(_panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btnPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btnPrincipalMouseClicked
       ventanaMain venMain = new ventanaMain();
       venMain.setVisible(true);
       this.dispose();
    }//GEN-LAST:event__btnPrincipalMouseClicked

    
    
public void setNombre(String pNombre){
    _lblClienteMostrar.setText(pNombre);

}    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnPrincipal;
    private javax.swing.JLabel _lblClienteMostrar;
    private javax.swing.JLabel _lblFecha;
    private javax.swing.JLabel _lblPago;
    private javax.swing.JPanel _panelFondo;
    private javax.swing.JTextArea _txtResultado;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
