/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author JoseR
 */
public class historial extends javax.swing.JFrame {

    /**
     * Creates new form historial
     */
    public historial() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _panelFondo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        _listResultados = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        _panelFondoRefinar = new javax.swing.JPanel();
        _lblRefinar = new javax.swing.JLabel();
        _dateDesde = new com.toedter.calendar.JDateChooser();
        _dateHasta = new com.toedter.calendar.JDateChooser();
        _lblDesdeFecha = new javax.swing.JLabel();
        _lblHastaFecha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        _btnPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _listResultados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(_listResultados);

        jLabel1.setText("Hitorial");

        _panelFondoRefinar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        _lblRefinar.setText("Refinar:");

        _lblDesdeFecha.setText("Desde");

        _lblHastaFecha.setText("Hasta");

        jButton1.setText("Buscar");

        javax.swing.GroupLayout _panelFondoRefinarLayout = new javax.swing.GroupLayout(_panelFondoRefinar);
        _panelFondoRefinar.setLayout(_panelFondoRefinarLayout);
        _panelFondoRefinarLayout.setHorizontalGroup(
            _panelFondoRefinarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_panelFondoRefinarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_panelFondoRefinarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _panelFondoRefinarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(_panelFondoRefinarLayout.createSequentialGroup()
                        .addGroup(_panelFondoRefinarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_lblDesdeFecha)
                            .addComponent(_lblHastaFecha))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(_panelFondoRefinarLayout.createSequentialGroup()
                        .addGroup(_panelFondoRefinarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_dateDesde, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addGroup(_panelFondoRefinarLayout.createSequentialGroup()
                                .addComponent(_lblRefinar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(_dateHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        _panelFondoRefinarLayout.setVerticalGroup(
            _panelFondoRefinarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_panelFondoRefinarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lblRefinar)
                .addGap(25, 25, 25)
                .addComponent(_lblDesdeFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_dateDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(_lblHastaFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_dateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        _btnPrincipal.setText("Principal");
        _btnPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _btnPrincipalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout _panelFondoLayout = new javax.swing.GroupLayout(_panelFondo);
        _panelFondo.setLayout(_panelFondoLayout);
        _panelFondoLayout.setHorizontalGroup(
            _panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(_panelFondoRefinar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(_panelFondoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(_btnPrincipal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );
        _panelFondoLayout.setVerticalGroup(
            _panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_panelFondoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(_panelFondoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50)
                        .addComponent(_panelFondoRefinar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_btnPrincipal))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btnPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__btnPrincipalMouseClicked
        ventanaMain vMain = new ventanaMain();
        vMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event__btnPrincipalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnPrincipal;
    private com.toedter.calendar.JDateChooser _dateDesde;
    private com.toedter.calendar.JDateChooser _dateHasta;
    private javax.swing.JLabel _lblDesdeFecha;
    private javax.swing.JLabel _lblHastaFecha;
    private javax.swing.JLabel _lblRefinar;
    private javax.swing.JList<String> _listResultados;
    private javax.swing.JPanel _panelFondo;
    private javax.swing.JPanel _panelFondoRefinar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
